#!/usr/bin/env python3
"""
Build searchable skill index shards with inlined descriptions.

Input:
  - data/skills_index.json (generated by the crawler)
  - description_en.txt files already generated under data/skills-md/**/description_en.txt

Output:
  - data/skills_search_index.json
  - data/skills_search_index2.json
  - data/skills_search_index3.json
  - ...

Design goals:
  - Fast lookup by id (map keyed by full skill id)
  - Deterministic output ordering for clean diffs
  - Keep each shard below GitHub's regular Git blob limit
  - No external dependencies
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
INDEX_PATH = DATA_DIR / "skills_index.json"
FIRST_SEEN_PATH = DATA_DIR / "skills_first_seen.json"

# Safety cap: descriptions should be short, but avoid accidental huge payloads.
MAX_DESCRIPTION_CHARS = 5000
# GitHub rejects regular Git blobs larger than 100,000,000 bytes.
GITHUB_GIT_BLOB_LIMIT_BYTES = 100_000_000
OUTPUT_STEM = "skills_search_index"
OUTPUT_SUFFIX = ".json"
OUTPUT_VERSION = 3
SHARD_SUFFIX = "\n  }\n}\n"


@dataclass(frozen=True)
class SerializedEntry:
    skill_id: str
    text: str
    size_bytes: int


def _utc_now_iso() -> str:
    # Keep diffs smaller and consistent with other generated JSON in this repo.
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _maybe_cn_path_from_en_path(repo_relative_path: Optional[str]) -> Optional[str]:
    """
    Given an English description path like:
      data/skills-md/<...>/description_en.txt
    return the sibling CN path:
      data/skills-md/<...>/description_cn.txt
    """
    if not repo_relative_path:
        return None
    s = str(repo_relative_path)
    if not s:
        return None
    if s.endswith("/description_en.txt"):
        return s[: -len("/description_en.txt")] + "/description_cn.txt"
    if s.endswith("\\description_en.txt"):
        return s[: -len("\\description_en.txt")] + "\\description_cn.txt"
    return None


def _load_first_seen_map() -> dict[str, str]:
    """
    Optional compatibility layer:
    - If `skills_index.json` items don't include `firstSeenAt` yet,
      we can still populate it from `data/skills_first_seen.json`.
    """
    if not FIRST_SEEN_PATH.exists():
        return {}
    try:
        data = json.loads(FIRST_SEEN_PATH.read_text(encoding="utf-8"))
        items = data.get("items") or {}
        if isinstance(items, dict):
            # Ensure values are strings (ISO timestamps).
            return {str(k): str(v) for k, v in items.items() if k and v}
    except Exception:
        pass
    return {}


def _read_text_repo_relative(repo_relative_path: Optional[str]) -> str:
    if not repo_relative_path:
        return ""
    rel = str(repo_relative_path).lstrip("/").strip()
    if not rel:
        return ""
    p = REPO_ROOT / rel
    try:
        return p.read_text(encoding="utf-8", errors="ignore")[:MAX_DESCRIPTION_CHARS].strip()
    except Exception:
        return ""


def _as_str(v: Any) -> str:
    if v is None:
        return ""
    if isinstance(v, str):
        return v
    return str(v)


def _search_index_filename(part: int) -> str:
    if part < 1:
        raise ValueError(f"part must be >= 1, got {part}")
    if part == 1:
        return f"{OUTPUT_STEM}{OUTPUT_SUFFIX}"
    return f"{OUTPUT_STEM}{part}{OUTPUT_SUFFIX}"


def _search_index_repo_relative_path(part: int) -> str:
    return f"data/{_search_index_filename(part)}"


def _search_index_path(part: int) -> Path:
    return DATA_DIR / _search_index_filename(part)


def _search_index_sort_key(path: Path) -> int:
    if path.name == f"{OUTPUT_STEM}{OUTPUT_SUFFIX}":
        return 1
    suffix = path.stem[len(OUTPUT_STEM) :]
    try:
        return int(suffix)
    except ValueError:
        return 1_000_000_000


def _json_scalar(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _serialize_entry(skill_id: str, item: dict[str, Any]) -> SerializedEntry:
    item_lines = json.dumps(item, ensure_ascii=False, indent=2).splitlines()
    entry_lines = [f'    {_json_scalar(skill_id)}: {item_lines[0]}']
    entry_lines.extend(f"    {line}" for line in item_lines[1:])
    text = "\n".join(entry_lines)
    return SerializedEntry(skill_id=skill_id, text=text, size_bytes=len(text.encode("utf-8")))


def _render_shard_prefix(
    *,
    updated_at: str,
    source_index_updated_at: Any,
    source_skills_updated_at: Any,
    files: list[str],
    part: int,
    total_parts: int,
    shard_count: int,
    total_count: int,
    start_id: str,
    end_id: str,
) -> str:
    lines = [
        "{",
        f'  "updatedAt": {_json_scalar(updated_at)},',
        f'  "sourceIndexUpdatedAt": {_json_scalar(source_index_updated_at)},',
        f'  "sourceSkillsUpdatedAt": {_json_scalar(source_skills_updated_at)},',
        f'  "version": {OUTPUT_VERSION},',
        f'  "part": {part},',
        f'  "totalParts": {total_parts},',
        f'  "count": {shard_count},',
        f'  "totalCount": {total_count},',
        f'  "startId": {_json_scalar(start_id)},',
        f'  "endId": {_json_scalar(end_id)},',
        '  "files": [',
    ]
    for idx, file_path in enumerate(files):
        comma = "," if idx < len(files) - 1 else ""
        lines.append(f"    {_json_scalar(file_path)}{comma}")
    lines.extend(
        [
            "  ],",
            '  "items": {',
        ]
    )
    return "\n".join(lines) + "\n"


def _shard_payload_bytes(
    *,
    updated_at: str,
    source_index_updated_at: Any,
    source_skills_updated_at: Any,
    files: list[str],
    part: int,
    total_parts: int,
    total_count: int,
    entries: list[SerializedEntry],
) -> bytes:
    if not entries:
        raise ValueError("Shard must contain at least one entry")

    prefix = _render_shard_prefix(
        updated_at=updated_at,
        source_index_updated_at=source_index_updated_at,
        source_skills_updated_at=source_skills_updated_at,
        files=files,
        part=part,
        total_parts=total_parts,
        shard_count=len(entries),
        total_count=total_count,
        start_id=entries[0].skill_id,
        end_id=entries[-1].skill_id,
    )
    body = ",\n".join(entry.text for entry in entries)
    return (prefix + body + SHARD_SUFFIX).encode("utf-8")


def _partition_entries(
    *,
    entries: list[SerializedEntry],
    updated_at: str,
    source_index_updated_at: Any,
    source_skills_updated_at: Any,
    total_parts: int,
) -> list[list[SerializedEntry]]:
    files = [_search_index_repo_relative_path(part) for part in range(1, total_parts + 1)]
    suffix_bytes = len(SHARD_SUFFIX.encode("utf-8"))
    total_count = len(entries)

    shards: list[list[SerializedEntry]] = []
    current_entries: list[SerializedEntry] = []
    current_entries_bytes = 0
    current_start_id = ""
    part = 1

    for entry in entries:
        candidate_entries = len(current_entries) + 1
        candidate_start_id = current_start_id or entry.skill_id
        prefix = _render_shard_prefix(
            updated_at=updated_at,
            source_index_updated_at=source_index_updated_at,
            source_skills_updated_at=source_skills_updated_at,
            files=files,
            part=part,
            total_parts=total_parts,
            shard_count=candidate_entries,
            total_count=total_count,
            start_id=candidate_start_id,
            end_id=entry.skill_id,
        )
        candidate_size = (
            len(prefix.encode("utf-8"))
            + current_entries_bytes
            + entry.size_bytes
            + (2 * (candidate_entries - 1))
            + suffix_bytes
        )

        if current_entries and candidate_size > GITHUB_GIT_BLOB_LIMIT_BYTES:
            shards.append(current_entries)
            part += 1
            current_entries = []
            current_entries_bytes = 0
            current_start_id = ""

            prefix = _render_shard_prefix(
                updated_at=updated_at,
                source_index_updated_at=source_index_updated_at,
                source_skills_updated_at=source_skills_updated_at,
                files=files,
                part=part,
                total_parts=total_parts,
                shard_count=1,
                total_count=total_count,
                start_id=entry.skill_id,
                end_id=entry.skill_id,
            )
            candidate_size = len(prefix.encode("utf-8")) + entry.size_bytes + suffix_bytes

        if candidate_size > GITHUB_GIT_BLOB_LIMIT_BYTES:
            raise SystemExit(
                f"Single search index entry {entry.skill_id!r} is {candidate_size:,} bytes with shard metadata, "
                f"which exceeds GitHub's regular Git blob limit of {GITHUB_GIT_BLOB_LIMIT_BYTES:,} bytes."
            )

        if not current_entries:
            current_start_id = entry.skill_id
        current_entries.append(entry)
        current_entries_bytes += entry.size_bytes

    if current_entries:
        shards.append(current_entries)

    return shards


def _build_shard_payloads(
    *,
    entries: list[SerializedEntry],
    updated_at: str,
    source_index_updated_at: Any,
    source_skills_updated_at: Any,
) -> list[tuple[Path, bytes, int]]:
    total_parts = 1

    while True:
        shards = _partition_entries(
            entries=entries,
            updated_at=updated_at,
            source_index_updated_at=source_index_updated_at,
            source_skills_updated_at=source_skills_updated_at,
            total_parts=total_parts,
        )
        if len(shards) == total_parts:
            break
        total_parts = len(shards)

    files = [_search_index_repo_relative_path(part) for part in range(1, total_parts + 1)]
    payloads: list[tuple[Path, bytes, int]] = []
    total_count = len(entries)

    for part, shard_entries in enumerate(shards, start=1):
        payload = _shard_payload_bytes(
            updated_at=updated_at,
            source_index_updated_at=source_index_updated_at,
            source_skills_updated_at=source_skills_updated_at,
            files=files,
            part=part,
            total_parts=total_parts,
            total_count=total_count,
            entries=shard_entries,
        )
        if len(payload) > GITHUB_GIT_BLOB_LIMIT_BYTES:
            raise SystemExit(
                f"{_search_index_path(part)} is {len(payload):,} bytes, which exceeds GitHub's "
                f"regular Git blob limit of {GITHUB_GIT_BLOB_LIMIT_BYTES:,} bytes."
            )
        payloads.append((_search_index_path(part), payload, len(shard_entries)))

    return payloads


def main() -> None:
    if not INDEX_PATH.exists():
        raise SystemExit(f"Missing {INDEX_PATH}. Run the crawler first.")

    index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    items = index.get("items") or []
    if not isinstance(items, list):
        raise SystemExit("skills_index.json: expected `items` to be a list")

    first_seen_by_id = _load_first_seen_map()

    by_id: dict[str, dict[str, Any]] = {}

    for it in items:
        if not isinstance(it, dict):
            continue
        full_id = _as_str(it.get("id")).strip()
        if not full_id:
            continue

        description_en_path = it.get("description")
        desc_en = _read_text_repo_relative(description_en_path)

        # Optional CN translation (same folder, description_cn.txt).
        description_cn_path = _maybe_cn_path_from_en_path(description_en_path)
        desc_cn = _read_text_repo_relative(description_cn_path) if description_cn_path else ""

        first_seen_at = it.get("firstSeenAt") or first_seen_by_id.get(full_id)

        # Keep the payload small and query-friendly.
        by_id[full_id] = {
            "id": full_id,
            "providerId": it.get("providerId"),
            "source": it.get("source"),
            "skillId": it.get("skillId"),
            "title": it.get("title"),
            "link": it.get("link"),
            "firstSeenAt": first_seen_at,
            "installsAllTime": it.get("installsAllTime"),
            "installsTrending": it.get("installsTrending"),
            "installsHot": it.get("installsHot"),
            # Inline descriptions for searching.
            # Keep `description` as EN for backward compatibility.
            "description": desc_en,
            "descriptionEn": desc_en,
            "descriptionCn": desc_cn or None,
            # Keep paths for debugging / refresh verification.
            "descriptionPath": description_en_path,
            "descriptionEnPath": description_en_path,
            "descriptionCnPath": description_cn_path if desc_cn else None,
            "skillMdPath": it.get("skillMdPath"),
        }

    updated_at = _utc_now_iso()
    source_index_updated_at = index.get("updatedAt")
    source_skills_updated_at = index.get("sourceUpdatedAt") or index.get("updatedAt")
    entries = [_serialize_entry(skill_id, item) for skill_id, item in sorted(by_id.items())]
    payloads = _build_shard_payloads(
        entries=entries,
        updated_at=updated_at,
        source_index_updated_at=source_index_updated_at,
        source_skills_updated_at=source_skills_updated_at,
    )

    expected_paths = {path for path, _, _ in payloads}
    for path, payload, shard_count in payloads:
        path.write_bytes(payload)
        print(f"Wrote {path} ({shard_count} skills, {len(payload):,} bytes)")

    for stale_path in sorted(DATA_DIR.glob(f"{OUTPUT_STEM}*.json"), key=_search_index_sort_key):
        if stale_path not in expected_paths:
            stale_path.unlink()
            print(f"Removed stale shard {stale_path}")

    print(f"Wrote {len(payloads)} search index shard(s) for {len(entries)} skills")


if __name__ == "__main__":
    main()
